# -*- mode: ruby -*-
# vi: set ft=ruby :

unless Vagrant.has_plugin?("vagrant-disksize")
  raise 'vagrant-disksize is not installed!'
end

Vagrant.configure("2") do |config|
  config.vm.hostname = "dev"

  config.vm.box = "bento/ubuntu-20.04"
  config.vm.provision :shell, path: "bootstrap.sh"

  config.ssh.forward_agent = true
  config.vm.network "forwarded_port", guest: 22, host: 20022, id: "ssh"

  config.disksize.size = '256GB'

  config.vm.provider "virtualbox" do |v|
    v.name = "dev"
    v.cpus = 12
    v.memory = 10240
  end
end
