# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.ssh.forward_agent = true

  config.vm.provider "virtualbox" do |v|
    v.cpus = 8
    v.memory = 8192
  end
end
